### ISSUE TITLE
Issue withSAP SuccessFactors Employee Central Payroll Integration with SAP S_4HANA or SAP ERP

### ISSUE THREAD

**Issue by kherenpm** [SAP/apibusinesshub-integration-recipes#57]
**Describe the bug**
Please I need to download the 3 TXT files described on page 10 of the document "Config Guide - Payroll Posting From SAP Succcessfactors Employee Central Payroll to S4HANA or SAP ERP"

<img width="881" alt="image" src="https://user-images.githubusercontent.com/105075410/167192739-43d3b010-55ac-4ecc-94a3-2d537f9cf30f.png">

**Comment by SAPAPIBusinessHub** [comment]
hello kherenpm,

I am trying to dig out the txt files...

Warm regards
aadi

**Comment by SAPAPIBusinessHub** [comment]
Files have been uploaded via commit: [fix for issue#57](https://github.com/SAP/apibusinesshub-integration-recipes/commit/0fc685a1c44ccab2633b8d040c7f0c23bfda349a )

**Comment by S0024178238** [comment]
I implemented the document but it doesn't work.
attached to the document.

[Isuue Santa Elena v.3.docx](https://github.com/SAP/apibusinesshub-integration-recipes/files/8952333/Isuue.Santa.Elena.v.3.docx)
